site_name: Algoritmi e Linguaggi di Programmazione Python/C
nav:
  - Home del corso: index.md
  - Slides proiettate a lezione: material/slides/index.md
  - Bacheca:
    - Avvisi: advices.md
    - Progetti: projects.md
  - Parte 1 - Concetti introduttivi:
    - 1 - Introduzione all'informatica: material/01_intro/01_introduction/lecture.md
    - 2 - Introduzione agli algoritmi: material/01_intro/02_algorithms/lecture.md
    - 3 - Tipi di dato: material/01_intro/03_data_type/lecture.md
    - 4 - Diagrammi di flusso: material/01_intro/04_flow_chart/lecture.md
    - 5 - Programmazione strutturata: material/01_intro/05_structured/lecture.md
    - 6 - Variabili: material/01_intro/06_variables/lecture.md
    - 7 - Funzioni: material/01_intro/07_functions/lecture.md
  - Parte 2 - Linguaggi di programmazione:
    - 8 - Introduzione al C: material/02_programming/08_intro_c/lecture.md
    - 9 - Nozioni fondamentali sul C:
      - Dispense: material/02_programming/09_c_fundamentals/lecture.md
      - Esercizi: material/02_programming/09_c_fundamentals/exercises.md
    - 10 - Introduzione al Python:
      - Dispense: material/02_programming/10_intro/lecture.md
      - Esercizi: material/02_programming/10_intro/exercises.md
    - 11 - Concetti sintattici fondamentali di Python:
      - Dispense: material/02_programming/11_syntax/lecture.md
      - Esercizi: material/02_programming/11_syntax/exercises.md
    - 12 - Programmazione orientata agli oggetti: material/02_programming/12_oop/lecture.md
    - 13 - OOP in Python:
      - Dispense: material/02_programming/13_classes/lecture.md
      - Esercizi: material/02_programming/13_classes/exercises.md
    - 14 - Strutture dati in Python:
      - Dispense: material/02_programming/14_data_structures/lecture.md
      - Esercizi: material/02_programming/14_data_structures/exercises.md
    - 15 - Moduli e script in Python: material/02_programming/15_modules/lecture.md
  - Appendici:
    - A - Installazione di VS Community: material/appendix/01_vs_comm/guide.md
    - B - Installazione di Python e VS Code: material/appendix/02_python_vs_code/guide.md
    - C - Il modulo argparse: material/appendix/04_argparse/lecture.md
    - D - Temi di esempio: material/appendix/05_sample_project/lecture.md

theme:
  name: material

markdown_extensions:
  - admonition # notes make pretty
  - attr_list
  - footnotes
  - meta # page-specific context
  - toc:
      permalink: true # inserts an anchor
  - sane_lists # better ul and ol
  - nl2br # newline hard break
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem: # better italic and bold
      smart_enable: asterisk
  - pymdownx.caret # insert text and superscript
  - pymdownx.details # details and summary; work with admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight: # better code, instead of CodeHilite           <--------
      linenums: false
  - pymdownx.inlinehilite # like codehilite but inline
  - pymdownx.magiclink # auto links
  - pymdownx.mark # highlight text
  - pymdownx.smartsymbols # special symbols
  - pymdownx.superfences: # nest code blocks under other blocks   <-------
  - pymdownx.tasklist: # better tasks lists
      custom_checkbox: true
  - pymdownx.tabbed # auto tabs
  - pymdownx.tilde # strike through cross out text
  - tables

plugin:
  - search
  - encryptcontent: {}

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/anhelus
    - icon: fontawesome/solid/paper-plane
      link: mailto:angelo.cardellicchio@stiima.cnr.it
  analytics:
    provider: google
    property: G-J2XESD8WDV

extra_javascript:
  - js/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; Angelo Cardellicchio - MIT License
