site_name: Corso di Informatica - Angelo Cardellicchio
nav:
  - Home del corso: index.md
  - Informazioni sul corso:
      - Ricevimento: ricevimento.md
      - Comunicare col docente: comunicazioni.md
      - Bacheca avvisi: bacheca.md
      - Esami:
          - Modalità standard: 01_esami/standard/intro.md
          - Tema d'anno:
              - Introduzione: 01_esami/tema_anno/intro.md
              - Valutazione: 01_esami/tema_anno/valutazione.md
              - FAQ: 01_esami/tema_anno/faq.md
              - A.A. 2020/2021:
                  - Date rilevanti: 01_esami/tema_anno/2020-2021/date.md
                  - Documenti: 01_esami/tema_anno/2020-2021/documenti.md
                  - Chiarimenti: 01_esami/tema_anno/2020-2021/chiarimenti.md
              - Esempio:
                  - Traccia: 01_esami/tema_anno/esempio/traccia.md
                  - Parte Prima: 01_esami/tema_anno/esempio/parte_prima.md
                  - Parte Seconda: 01_esami/tema_anno/esempio/parte_seconda.md
                  - Parte Terza: 01_esami/tema_anno/esempio/parte_terza.md
  - Dispense:
      - Slides proiettate a lezione: 00_materiale/programma.md
      - Teoria:
          - Concetti Introduttivi:
              - 01 - Introduzione all'Informatica: 02_dispense/01_introduttivi/01_intro.md
              - 02 - Gli Algoritmi: 02_dispense/01_introduttivi/02_algoritmi.md
              # - 03 - Diagrammi di flusso: 01_introduttivi/03_diagrammi.md
              - 04 - Rappresentazione dei dati: 02_dispense/01_introduttivi/04_rappresentazione.md
          #   - L'Hardware:
          #     - 05 - Architettura dei Calcolatori: 02_hardware/01_architettura.md
          #     - 06 - Reti di Calcolatori: 02_hardware/02_reti.md
          #   - Linguaggi:
          #     - 07 - Linguaggi di Programmazione: 03_linguaggi/01_linguaggi.md
          #     - 08 - Traduttori: 03_linguaggi/02_traduttori.md
          - Programmazione:
              # - 09 - Programmazione strutturata: 04_programmazione/01_strutturata.md
              # - 10 - Ricorsione: 04_programmazione/02_ricorsione.md
              - 11 - Variabili: 02_dispense/04_programmazione/03_variabili.md
              - 12 - Funzioni: 02_dispense/04_programmazione/04_funzioni.md
              - 13 - Complessità computazionale: 02_dispense/04_programmazione/05_complessita.md
              - 14 - Strutture dati: 02_dispense/04_programmazione/06_strutture_dati.md
          - Algoritmi:
              #- 14 - Ricerca dicotomica: 05_algoritmi/01_binary_search.md
              #- 15 - Selection sort: 05_algoritmi/02_selection_sort.md
              #- 16 - Insertion sort: 05_algoritmi/03_insertion_sort.md
              - 17 - Merge sort: 02_dispense/05_algoritmi/04_merge_sort.md
              - 18 - Quick sort: 02_dispense/05_algoritmi/05_quick_sort.md
            # - 19 - Breadth-first search: 05_algoritmi/06_bfs.md
          - Modelli di calcolo:
              - 20 - Macchina di Turing: 02_dispense/06_modelli/01_turing.md
      - Programmazione:
          - Linguaggio C:
              - 01 - Introduzione al C: 02_dispense/programmazione/01_linguaggio_c/01_introduzione.md
          - Linguaggio C++:
              - 01 - C vs. C++: 02_dispense/programmazione/02_linguaggio_cpp/01_c_vs_cpp.md
              - 02 - Alcune definizioni (in C++!): 02_dispense/programmazione/02_linguaggio_cpp/02_definizioni.md
              - 03 - Le classi (parte uno): 02_dispense/programmazione/02_linguaggio_cpp/03_classi.md
              - 04 - Alcune definizioni (più avanzate): 02_dispense/programmazione/02_linguaggio_cpp/04_definizioni_adv.md
              - 05 - Le classi (parte due): 02_dispense/programmazione/02_linguaggio_cpp/05_classi_adv.md
              - 06 - Dettagli sui metodi: 02_dispense/programmazione/02_linguaggio_cpp/06_metodi.md
              - 07 - Ereditarietà: 02_dispense/programmazione/02_linguaggio_cpp/07_ereditarieta.md
              - 08 - Polimorfismo: 02_dispense/programmazione/02_linguaggio_cpp/08_polimorfismo.md
              - 09 - Container ed iteratori: 02_dispense/programmazione/02_linguaggio_cpp/09_container.md
              - 10 - File in C++: 02_dispense/programmazione/02_linguaggio_cpp/10_file.md
          - Linugaggio Python:
              - 01 - Introduzione al Python: 02_dispense/programmazione/03_linguaggio_python/01_intro.md
              - 02 - Programmare in Python: 02_dispense/programmazione/03_linguaggio_python/02_programmare.md
              - 03 - Strutture Dati: 02_dispense/programmazione/03_linguaggio_python/03_strutture.md
              - 04 - Moduli: 02_dispense/programmazione/03_linguaggio_python/04_moduli.md
  - Appendici:
      - Configurazioni:
          - Visual Studio Code: 03_appendici/configurazioni/a_vs_code_guide.md
          - Visual Studio Community: 03_appendici/configurazioni/b_vs_community_guide.md
  - Esercizi:
      - Linguaggio C: 04_esercizi/linguaggio_c.md

theme:
  name: material

markdown_extensions:
  - admonition # notes make pretty
  - attr_list
  - footnotes
  - meta # page-specific context
  - toc:
      permalink: true # inserts an anchor
  - sane_lists # better ul and ol
  - nl2br # newline hard break
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem: # better italic and bold
      smart_enable: asterisk
  - pymdownx.caret # insert text and superscript
  - pymdownx.details # details and summary; work with admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight: # better code, instead of CodeHilite           <--------
      linenums: false
  - pymdownx.inlinehilite # like codehilite but inline
  - pymdownx.magiclink # auto links
  - pymdownx.mark # highlight text
  - pymdownx.smartsymbols # special symbols
  - pymdownx.superfences: # nest code blocks under other blocks   <-------
  - pymdownx.tasklist: # better tasks lists
      custom_checkbox: true
  - pymdownx.tabbed # auto tabs
  - pymdownx.tilde # strike through cross out text

extra_javascript:
  - js/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
