site_name: Corso di Informatica

nav:
  - Home: index.md
  - Tracce di esame svolte:
    - Traccia del 17 gennaio 2024: material/exams/17_01_24/exam.md
    # - Traccia del 07 febbraio 2024: material/exams/07_02_24/exam.md
    # - Traccia del 17 aprile 2024: material/exams/17_04_24/exam.md
  - 1. Introduzione:
    - 1.1 Introduzione all'informatica: material/01_intro/01_intro_inf.md
    - 1.2 Rappresentazione dei dati: material/01_intro/02_data_repr.md
    - 1.3 Codifica digitale ed analogica: material/01_intro/03_dig_an.md
    - 1.4 Sistemi di numerazione: material/01_intro/04_num_sis.md
    - 1.5 Sistema binario: material/01_intro/05_sis_bin.md
    - 1.6 Data types: material/01_intro/06_data_types.md
  - Algoritmi di ordinamento:
    - Selection sort: material/new/13_algorithms/01_selection_sort.md
  # - 1 - Introduzione all'informatica: material/01_intro/01_introduction/lecture.md
  # - 2 - Introduzione agli algoritmi: material/01_intro/02_algorithms/lecture.md
  # - 3 - Numeri decimali e binari: material/01_intro/03_dec_bin/lecture.md
  # - 4 - Tipi di dato: material/01_intro/04_data_type/lecture.md
  # - 5 - Diagrammi di flusso: material/01_intro/05_flow_chart/lecture.md
  # - 6 - Programmazione strutturata: material/01_intro/06_structured/lecture.md
  # - 7 - Variabili: material/01_intro/07_variables/lecture.md
  # - 8 - Funzioni: material/01_intro/08_functions/lecture.md
  # - 9 - Complessità computazionale:
  #   - Dispense: material/01_intro/09_complexity/lecture.md
  #   - Esercizi: material/01_intro/09_complexity/exercises.md
  # - 10 - Strutture dati: material/01_intro/10_data_structures/lecture.md
  # - 11 - Ricorsione: material/01_intro/11_recursion/lecture.md
  # - 12 - Paradigmi di programmazione: material/01_intro/12_paradigms/lecture.md
  # - 13 - Strutture dati avanzate: material/01_intro/13_adv_data_structures/lecture.md
  # - 14 - Selection sort: material/02_algorithms/14_sorting/selection_sort.md

theme:
  name: material
  language: it

markdown_extensions:
  - admonition # notes make pret4ty
  - attr_list
  - footnotes
  - meta # page-specific context
  - toc:
      permalink: true # inserts an anchor
  - sane_lists # better ul and ol
  - nl2br # newline hard break
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem: # better italic and bold
      smart_enable: asterisk
  - pymdownx.caret # insert text and superscript
  - pymdownx.details # details and summary; work with admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight: # better code, instead of CodeHilite           <--------
      anchor_linenums: false
  - pymdownx.inlinehilite # like codehilite but inline
  - pymdownx.magiclink # auto links
  - pymdownx.mark # highlight text
  - pymdownx.smartsymbols # special symbols
  - pymdownx.superfences: # nest code blocks under other blocks   <-------
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist: # better tasks lists
      custom_checkbox: true
  - pymdownx.tabbed: # auto tabs
      alternate_style: true # auto tabs
  - pymdownx.tilde # strike through cross out text
  - tables
  - md_in_html

plugin:
  - search
  - encryptcontent: {}

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/anhelus
    - icon: fontawesome/solid/paper-plane
      link: mailto:angelo.cardellicchio@poliba.it
  analytics:
    provider: google
    property: G-J2XESD8WDV

extra_javascript:
  - js/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; Angelo Cardellicchio - MIT License
