site_name: Corso di Informatica

nav:
  - Home: index.md
  - Tracce di esame svolte:
    - Traccia del 17 gennaio 2024: material/exams/17_01_24/exam.md
  - Parte 1:
    - 1 Introduzione all'informatica: material/01_intro/01_intro_inf.md
    - 2 Rappresentazione dei dati: material/01_intro/02_data_repr.md
    - 3 Codifica digitale ed analogica: material/01_intro/03_dig_an.md
    - 4 Sistemi di numerazione: material/01_intro/04_num_sis.md
    - 5 Sistema binario: material/01_intro/05_sis_bin.md
    - 6 Dimensione dei dati: material/01_intro/06_data_types.md
    - 7 Algebra di Boole:
      - 7.1 Introduzione: material/01_intro/07_boole/01_intro.md
      - 7.2 Operazioni fondamentali: material/01_intro/07_boole/02_ops.md
      - 7.3 Proprietà delle operazioni fondamentali: material/01_intro/07_boole/03_ops_properties.md
      - 7.4 Leggi dell'algebra booleana: material/01_intro/07_boole/04_laws.md
  # - 2 Programmare:
  #   - 2.1 Diagrammi di flusso: material/02_programming/01_flow_chart/lecture.md
  #   - 2.2 Programmazione strutturata: material/02_programming/02_structured/lecture.md
  #   - 2.3 Ricorsione: material/02_programming/03_recursion/lecture.md
  #   - 2.4 Variabili: material/02_programming/04_variables/lecture.md
  #   - 2.5 Funzioni: material/02_programming/05_functions/lecture.md
  #   - 2.6 Complessità computazionale: material/02_programming/06_complexity/lecture.md
  #   - 2.7 Strutture dati: material/02_programming/07_data_structures/lecture.md
  #   - 2.8 Strutture dati avanzate: material/02_programming/08_adv_data_structures/lecture.md
  #   - 2.9 Paradigmi di programmazione: material/02_programming/09_paradigms/lecture.md
  - Parte 3:
    # - 3.1 Introduzione agli algoritmi: material/03_algorithms/01_intro/lecture.md
    # - 3.2 Algoritmi di ordinamento:
    - 3.2.1 Selection sort: material/new/13_algorithms/01_selection_sort.md
    # - 3.3 Algoritmi di ricerca: material/03_algorithms/03_search/lecture.md
  # - 4 Architettura e principi dei calcolatori:
  #   - 4.1 Architettura: material/04_architecture/01_architecture.md
  #   - 4.2 Sistemi operativi: material/04_architecture/02_os.md
    

theme:
  name: material
  language: it

markdown_extensions:
  - admonition # notes make pret4ty
  - attr_list
  - footnotes
  - meta # page-specific context
  - toc:
      permalink: true # inserts an anchor
  - sane_lists # better ul and ol
  - nl2br # newline hard break
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem: # better italic and bold
      smart_enable: asterisk
  - pymdownx.caret # insert text and superscript
  - pymdownx.details # details and summary; work with admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight: # better code, instead of CodeHilite           <--------
      anchor_linenums: false
  - pymdownx.inlinehilite # like codehilite but inline
  - pymdownx.magiclink # auto links
  - pymdownx.mark # highlight text
  - pymdownx.smartsymbols # special symbols
  - pymdownx.superfences: # nest code blocks under other blocks   <-------
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist: # better tasks lists
      custom_checkbox: true
  - pymdownx.tabbed: # auto tabs
      alternate_style: true # auto tabs
  - pymdownx.tilde # strike through cross out text
  - tables
  - md_in_html

# plugin:
#   - search
#   - encryptcontent: {}

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/anhelus
    - icon: fontawesome/solid/paper-plane
      link: mailto:angelo.cardellicchio@poliba.it
  analytics:
    provider: google
    property: G-J2XESD8WDV

extra_javascript:
  - js/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; Angelo Cardellicchio - MIT License
