site_name: Informatica - Corso di Laurea in Matematica - UniBa
nav:
  - Concetti Introduttivi:
    - 01 - Introduzione all'Informatica: 01_introduttivi/01_intro.md
    - 02 - Gli Algoritmi: 01_introduttivi/02_algoritmi.md
    - 03 - Rappresentazione dei dati: 01_introduttivi/03_rappresentazione.md
#   - L'Hardware:
    # - 04 - Architettura dei Calcolatori: 03_architettura.md
    # - 05 - Reti di Calcolatori: 05_reti.md
#   - I Linguaggi:
    # - 06 - Linguaggi di programmazione: 06_linguaggi.md
    # - 07 - Compilatori e interpreti: 07_traduttori.md
#   -  Linguaggi di programmazione:
#     - 06 - Linguaggi: 06_linguaggi.md
#     - 07 - Traduttori: 07_traduttori.md
#   - 08 - Macchina di Turing: 08_turing.md
#   - 09 - Complessità computazionale: 09_complessita.md

theme:
  name: material

markdown_extensions:
  - admonition # notes make pretty
  - attr_list
  - footnotes
  - meta # page-specific context
  - toc:
      permalink: true # inserts an anchor
  - sane_lists # better ul and ol
  - nl2br # newline hard break
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem: # better italic and bold
      smart_enable: asterisk
  - pymdownx.caret # insert text and superscript
  - pymdownx.details # details and summary; work with admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight: # better code, instead of CodeHilite           <--------
      linenums: false
  - pymdownx.inlinehilite # like codehilite but inline
  - pymdownx.magiclink # auto links
  - pymdownx.mark # highlight text
  - pymdownx.smartsymbols # special symbols
  - pymdownx.superfences: # nest code blocks under other blocks   <-------
  - pymdownx.tasklist: # better tasks lists
      custom_checkbox: true
  - pymdownx.tabbed # auto tabs
  - pymdownx.tilde # strike through cross out text

extra_javascript:
  - js/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js