site_name: Informatica - Corso di Laurea in Matematica - UniBa
nav:
  - Concetti Introduttivi:
    - 01 - Introduzione all'Informatica: 01_introduttivi/01_intro.md
    - 02 - Gli Algoritmi: 01_introduttivi/02_algoritmi.md
    # - 03 - Diagrammi di flusso: 01_introduttivi/03_diagrammi.md
    - 04 - Rappresentazione dei dati: 01_introduttivi/03_rappresentazione.md
#   - L'Hardware:
#     - 05 - Architettura dei Calcolatori: 02_hardware/01_architettura.md
#     - 06 - Reti di Calcolatori: 02_hardware/02_reti.md
#   - Linguaggi:
#     - 07 - Linguaggi di Programmazione: 03_linguaggi/01_linguaggi.md
#     - 08 - Traduttori: 03_linguaggi/02_traduttori.md
  - Programmazione:
    # - 09 - Programmazione strutturata: 04_programmazione/01_strutturata.md
    - 10 - Variabili: 04_programmazione/02_variabili.md
    - 11 - Funzioni: 04_programmazione/03_funzioni.md
    - 12 - Complessità computazionale: 04_programmazione/04_complessita.md
#   - Algoritmi:
#     - 13 - Ricerca dicotomica: 05_algoritmi/01_binary_search.md
#   - Automi:
# - 13 - Grammatiche
#     - 13 - Automi: 05_automi/01_automi.md
#     - 14 - Macchina di Turing: 05_automi/02_turing.md
#   - Il linguaggio C:
#     - 01 - Introduzione al C: 06_linguaggio_c/01_introduzione.md

theme:
  name: material

markdown_extensions:
  - admonition # notes make pretty
  - attr_list
  - footnotes
  - meta # page-specific context
  - toc:
      permalink: true # inserts an anchor
  - sane_lists # better ul and ol
  - nl2br # newline hard break
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem: # better italic and bold
      smart_enable: asterisk
  - pymdownx.caret # insert text and superscript
  - pymdownx.details # details and summary; work with admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight: # better code, instead of CodeHilite           <--------
      linenums: false
  - pymdownx.inlinehilite # like codehilite but inline
  - pymdownx.magiclink # auto links
  - pymdownx.mark # highlight text
  - pymdownx.smartsymbols # special symbols
  - pymdownx.superfences: # nest code blocks under other blocks   <-------
  - pymdownx.tasklist: # better tasks lists
      custom_checkbox: true
  - pymdownx.tabbed # auto tabs
  - pymdownx.tilde # strike through cross out text

extra_javascript:
  - js/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js