site_name: Corso di Informatica

nav:
  - Home: index.md
  - 1. Introduzione all'informatica:
    - 1.1 Introduzione all'informatica: material/01_intro/01_intro_inf.md
    - 1.2 Rappresentazione dei dati: material/01_intro/02_data_repr.md
    - 1.3 Codifica digitale ed analogica: material/01_intro/03_dig_an.md
    - 1.4 Sistemi di numerazione: material/01_intro/04_num_sis.md
    - 1.5 Sistema binario: material/01_intro/05_sis_bin.md
    - 1.6 Dimensione dei dati: material/01_intro/06_data_types.md
    - 1.7 Algebra di Boole:
      - 1.7.1 Introduzione: material/01_intro/07_boole/01_intro.md
      - 1.7.2 Operazioni fondamentali: material/01_intro/07_boole/02_ops.md
      - 1.7.3 Proprietà delle operazioni fondamentali: material/01_intro/07_boole/03_ops_properties.md
      - 1.7.4 Leggi dell'algebra booleana: material/01_intro/07_boole/04_laws.md
  - 2. Principi di programmazione:
    - 2.1 Gli algoritmi: material/02_programming/01_algorithms/lecture.md
    - 2.2 La programmmazione strutturata: 
      - 2.2.1 Introduzione: material/02_programming/02_structured/01_intro/lecture.md
      - 2.2.2 I diagrammi di flusso: material/02_programming/02_structured/02_flow_charts/lecture.md
      # - 2.2.3 Pseudocodice: material/02_programming/02_structured/03_pseudocode/lecture.md
    - 2.3 La ricorsione: material/02_programming/03_recursion/lecture.md
    - 2.4 Le variabili: material/02_programming/04_variables/lecture.md
    - 2.5 Le funzioni:
      - 2.5.1 Introduzione: material/02_programming/05_functions/01_intro/lecture.md
      # - 2.5.2 Parametri formali ed attuali: material/02_programming/05_functions/02_parameters/lecture.md
      # - 2.5.3 Funzioni e procedure: material/02_programming/05_functions/03_procedures/lecture.md
    - 2.6 Complessità computazionale: material/02_programming/06_complexity/lecture.md
    - 2.7 Strutture dati:
      - 2.7.1 Strutture dati base: material/02_programming/07_data_structures/01_intro/lecture.md
      - 2.7.2 Strutture dati avanzate: material/02_programming/07_data_structures/02_advanced/lecture.md
    - 2.8 Paradigmi di programmazione: material/02_programming/08_paradigms/lecture.md
  - 3. Algoritmi:
    - 3.1 Algoritmi di ordinammento:
      - 3.1.1 Selection sort: material/03_algorithms/01_sorting/01_selection/lecture.md
      # - 3.1.2 Bubble sort: material/03_algorithms/01_sorting/02_bubble/lecture.md
      # - 3.1.3 Insertion sort: material/03_algorithms/01_sorting/03_insertion/lecture.md
    # - 3.2 Algoritmi di ricerca:
    #   - 3.2.1 Ricerca lineare: material/03_algorithms/02_search/01_linear/lecture.md
    #   - 3.2.2 Ricerca binaria: material/03_algorithms/02_search/02_binary/lecture.md
  # - 4. Architettura dei calcolatori:
  #   - 4.1 L'architettura di Von Neumann: material/04_architecture/01_von_neumann/lecture.md 
  # - 5 - Sistemi operativi:
  #   - 5.1 Introduzione ai sistemi operativi: material/05_os/01_intro/lecture.md
  #   - 5.2 Il Kernel: material/05_os/02_kernel/lecture.md
  - 6 Ingegneria del software:
    - 6.1.1 Introduzione all'ingegneria del software: material/06_isw/01_intro/01_intro.md 
    - 6.1.2 Classificazione del software: material/06_isw/01_intro/02_classification.md
    - 6.1.3 Caratteristiche del software: material/06_isw/01_intro/03_characteristics.md
    - 6.1.4 Qualità del software: material/06_isw/01_intro/04_quality.md
    - 6.1.5 Requisiti del software: material/06_isw/01_intro/05_requirements.md

theme:
  name: material
  language: it

markdown_extensions:
  - admonition # notes make pret4ty
  - attr_list
  - footnotes
  - meta # page-specific context
  - toc:
      permalink: true # inserts an anchor
  - sane_lists # better ul and ol
  - nl2br # newline hard break
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem: # better italic and bold
      smart_enable: asterisk
  - pymdownx.caret # insert text and superscript
  - pymdownx.details # details and summary; work with admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight: # better code, instead of CodeHilite           <--------
      anchor_linenums: false
  - pymdownx.inlinehilite # like codehilite but inline
  - pymdownx.magiclink # auto links
  - pymdownx.mark # highlight text
  - pymdownx.smartsymbols # special symbols
  - pymdownx.superfences: # nest code blocks under other blocks   <-------
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist: # better tasks lists
      custom_checkbox: true
  - pymdownx.tabbed: # auto tabs
      alternate_style: true # auto tabs
  - pymdownx.tilde # strike through cross out text
  - tables
  - md_in_html

# plugin:
#   - search
#   - encryptcontent: {}

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/anhelus
    - icon: fontawesome/solid/paper-plane
      link: mailto:angelo.cardellicchio@poliba.it
  analytics:
    provider: google
    property: G-J2XESD8WDV

extra_javascript:
  - js/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; Angelo Cardellicchio - MIT License
